language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_install:
  - cd client
script:
  - npm run build
before_deploy:
  - cd dist
deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true
